version: '3.8'

services:
  app:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak-app
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: mariadb
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_DATABASE}
      KC_DB_SCHEMA: ${KEYCLOAK_DB_DATABASE}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
    command: start
    networks:
      - frontnet
      - backnet
    expose:
      - 8080

  db:
    image: jc21/mariadb-aria:10.11.5
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${KEYCLOAK_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${KEYCLOAK_DB_DATABASE}
      MYSQL_USER: ${KEYCLOAK_DB_USER}
      MYSQL_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/keycloak/mysql:/var/lib/mysql
    expose:
      - 3306
    networks:
      - backnet

networks:
  frontnet:
    name: frontnet
    external: true
  backnet:
    name: backnet
    external: true