version: '3.8'

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    privileged: true
    container_name: nginx-proxy-manager-app
    restart: unless-stopped
    environment:
      DB_MYSQL_HOST: nginx-proxy-manager-db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - app_data:/data
      - letsencrypt_data:/etc/letsencrypt
      - /etc/docker/nginx-proxy-manager:/data/nginx/custom
    ports:
      - 80:80
      - 443:443
      # Admin Dashboard Port, remove after setting up a corresponding host and exposing it instead
      - 81:81
    networks:
      - frontnet
      - backnet
    healthcheck:
      test: [ "CMD", "/bin/check-health" ]
      interval: 10s
      timeout: 3s
    depends_on:
      - db

  db:
    image: jc21/mariadb-aria:latest
    container_name: nginx-proxy-manager-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - backnet

# Set 'external' to 'false' for volumes and networks, if they don't already exist

volumes:
  app_data:
    name: nginx-proxy-manager_app_data
    external: true
  letsencrypt_data:
    name: nginx-proxy-manager_letsencrypt_data
    external: true
  db_data:
    name: nginx-proxy-manager_db_data
    external: true

networks:
  frontnet:
    name: frontnet
    external: true
  backnet:
    name: backnet
    external: true
