version: '3.8'

services:
  app:
    image: jc21/nginx-proxy-manager:2.10.4
    container_name: nginx-proxy-manager-app
    restart: unless-stopped
    privileged: true
    environment:
      DB_MYSQL_HOST: ${NGINX_PM_DB_HOST:-nginx-proxy-manager-db}
      DB_MYSQL_PORT: ${NGINX_PM_DB_PORT:-3306}
      DB_MYSQL_NAME: ${NGINX_PM_DB_DATABASE}
      DB_MYSQL_USER: ${NGINX_PM_DB_USER}
      DB_MYSQL_PASSWORD: ${NGINX_PM_DB_PASSWORD}
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/nginx-proxy-manager/data:/data
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/nginx-proxy-manager/config:/data/nginx/custom
    ports:
      - 80:80
      - 443:443
    expose:
      - 81
    networks:
      - frontnet
      - backnet
    healthcheck:
      test: [ "CMD", "/bin/check-health" ]
      interval: 10s
      timeout: 3s
    depends_on:
      - db

  db:
    image: jc21/mariadb-aria:10.11.5
    container_name: nginx-proxy-manager-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${NGINX_PM_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NGINX_PM_DB_DATABASE}
      MYSQL_USER: ${NGINX_PM_DB_USER}
      MYSQL_PASSWORD: ${NGINX_PM_DB_PASSWORD}
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/nginx-proxy-manager/mysql:/var/lib/mysql
    expose:
      - 3306
    networks:
      - backnet

networks:
  frontnet:
    name: frontnet
    external: true
  backnet:
    name: backnet
    external: true