version: '3.8'

services:
  backend:
    image: ghcr.io/tilokowalski/tickets-backend:latest
    container_name: tickets-backend
    restart: unless-stopped
    environment:
      APP_LOG_LEVEL: info
      APP_PROFILE: prod
      APP_DB_HOST: tickets-db
      APP_DB_NAME: ${MYSQL_DATABASE}
      APP_DB_USER: ${MYSQL_USER}
      APP_DB_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 8080
    networks:
      - frontnet
      - backnet
    depends_on:
      - db

  db:
    image: jc21/mariadb-aria:latest
    container_name: tickets-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - backnet

volumes:
  db_data:
    name: tickets_db_data
    external: true

networks:
  frontnet:
    external: true
  backnet:
    external: true
