version: '3.8'

secrets:
  MYSQL_ROOT_PASSWORD:
    file: .secrets/mysql_root_password.txt
  MYSQL_DATABASE:
    file: .secrets/mysql_database.txt
  MYSQL_USER:
    file: .secrets/mysql_user.txt
  MYSQL_PASSWORD:
    file: .secrets/mysql_password.txt

services:
  backend:
    image: ghcr.io/tilokowalski/tickets-backend:0.0.1-SNAPSHOT
    container_name: tickets-backend
    restart: unless-stopped
    secrets:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    environment:
      APP_LOG_LEVEL: info
      APP_PROFILE: prod
      APP_DB_HOST: tickets-db
      APP_DB_NAME__FILE: /run/secrets/MYSQL_DATABASE
      APP_DB_USER__FILE: /run/secrets/MYSQL_USER
      APP_DB_PASSWORD__FILE: /run/secrets/MYSQL_PASSWORD
    expose:
      - 8080
    networks:
      - frontnet
      - backnet
    depends_on:
      - db

  db:
    image: jc21/mariadb-aria:latest
    container_name: tickets-db
    restart: unless-stopped
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    environment:
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE__FILE: /run/secrets/MYSQL_DATABASE
      MYSQL_USER__FILE: /run/secrets/MYSQL_USER
      MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - backnet

volumes:
  db_data:
    name: tickets_db_data
    external: true

networks:
  frontnet:
    external: true
  backnet:
    external: true
